name: Lint Review

on:
  push:
    branches-ignore:
      - renovate/**
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node LTS
        uses: actions/setup-node@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - run: npm i -g prettier

      - name: Checkout code
        uses: actions/checkout@v3
        if: ${{ github.event_name != 'push' }}
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Checkout code
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'push' }}

      - name: prettier
        run: prettier --write --list-different ./

      - name: gofmt
        run: gofmt -w -s .

      - run: git diff --exit-code

      - uses: reviewdog/action-setup@v1
        if: ${{ failure() && github.event_name != 'push' }}
        with:
          reviewdog_version: latest

      - name: create review
        if: ${{ failure() && github.event_name != 'push' }}
        run: |
          TMPFILE=$(mktemp)
          content=$(git diff --name-only|sort|head -n |xargs git diff --)
          echo "${content}" >"${TMPFILE}"
          git reset --hard HEAD

          reviewdog -f=diff -f.diff.strip=1 -reporter=github-pr-review -tee < "${TMPFILE}"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
