name: release

on:
  push:
    tags:
      - "v*.*.*"
env:
  USER: "bangumi"
  IMAGE: "chii"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "~1.17.8"

      - name: Get Tag Name
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - run: make build

      - name: docker build
        run: docker build -t ghcr.io/${{ env.USER }}/${{ env.IMAGE }}:latest .

      - name: docker login
        run: echo $DOCKER_TOKEN | docker login ghcr.io -u ${{ env.USER }} --password-stdin
        env:
          DOCKER_TOKEN: ${{ github.token }}

      - name: docker push
        run: |
          docker push ghcr.io/${{ env.USER }}/${{ env.IMAGE }}:latest
          docker tag ghcr.io/${{ env.USER }}/${{ env.IMAGE }}:latest "ghcr.io/${{ env.USER }}/${{ env.IMAGE }}:$TAG"
          docker push "ghcr.io/${{ env.USER }}/${{ env.IMAGE }}:$TAG"

      - name: Generate Changlog
        run: |
          docker pull quay.io/git-chglog/git-chglog:latest
          docker run -v "$PWD":/workdir quay.io/git-chglog/git-chglog "$TAG" | \
          python -c 'import sys;print("".join(sys.stdin.readlines()[3:]).strip())' > changelog.md

      - name: Upload GitHub Release
        run: gh release create "$TAG" --title "$TAG" -F changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
